apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "minio.fullname" . }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "minio.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "minio.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          args:
            - server
            - /data
            - --console-address
            - :{{ .Values.minio.consolePort }}
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsUser: 100
            runAsGroup: 101
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: api
              containerPort: {{ .Values.minio.apiPort }}
              protocol: TCP
            - name: console
              containerPort: {{ .Values.minio.consolePort }}
              protocol: TCP
          env:
            - name: MINIO_BROWSER_REDIRECT_URL
              value: "{{ .Values.minio.browserRedirectURL }}"
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.secretName }}"
                  key: minio_root_user
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.secretName }}"
                  key: minio_root_password
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: api
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /minio/health/live
              port: api
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: data
              mountPath: /data
            - name: minio
              mountPath: /.minio
      volumes:
        - name: data
          hostPath:
            path: {{ .Values.volumeHost.path }}
            type: Directory
        - name: minio
          emptyDir:
            medium: Memory
