apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.fullname" . }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.minio.apiPort }}
      targetPort: api
      protocol: TCP
      name: api
    - port: {{ .Values.minio.consolePort }}
      targetPort: console
      protocol: TCP
      name: console
  selector:
    {{- include "minio.selectorLabels" . | nindent 4 }}
