{{- $fullName := include "webapp.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  {{- with .Values.deployment.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "webapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "webapp.selectorLabels" . | nindent 8 }}
        {{- if .Values.podAdditionalLabels }}
        {{- toYaml .Values.podAdditionalLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create -}}
      serviceAccountName: {{ include "webapp.serviceAccountName" . }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if and .Values.volumes .Values.podSecurityContext.fsGroup }}
      initContainers:
        - name: setup-volumes
          image: "busybox:latest"
          command:
            - sh
            - -ec
            - |
              {{- $fsGroup := .Values.podSecurityContext.fsGroup }}
              {{- range $name, $prop := .Values.volumes }}
              chgrp {{ $fsGroup }} {{ $prop.mountPath | quote }}
              chmod 0770 {{ $prop.mountPath | quote }}
              {{- end }}
          volumeMounts:
            {{- range $name, $prop := .Values.volumes }}
            - name: {{ $name }}
              mountPath: {{ $prop.mountPath }}
            {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.lifecycle }}
          lifecycle:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.volumes .Values.tmpfs .Values.hostPath }}
          volumeMounts:
            {{- range $name, $prop := .Values.tmpfs }}
            - name: {{ $name }}
              mountPath: {{ $prop.mountPath }}
            {{- end }}
            {{- range $name, $prop := .Values.volumes }}
            - name: {{ $name }}
              mountPath: {{ $prop.mountPath }}
              {{- with $prop.readOnly }}
              readOnly: {{ .  }}
              {{- end }}
            {{- end }}
            {{- range $name, $prop := .Values.hostPath }}
            - name: {{ $name }}
              mountPath: {{ $prop.mountPath }}
              {{- with $prop.readOnly }}
              readOnly: {{ . }}
              {{- end }}
            {{- end }}
          {{- end }}
      {{- if or .Values.volumes .Values.tmpfs .Values.hostPath }}
      volumes:
      {{- range $name, $prop := .Values.tmpfs }}
        - name: {{ $name }}
          emptyDir:
            medium: Memory
      {{- end }}
      {{- range $name, $prop := .Values.volumes }}
        - name: {{ $name }}
          persistentVolumeClaim:
            claimName: {{ $fullName }}-{{ $name }}
      {{- end }}
      {{- range $name, $prop := .Values.hostPath }}
        - name: {{ $name }}
          hostPath:
            path: {{ $prop.path }}
            type: Directory
      {{- end }}
      {{- end }}
