{{ if .Values.ingress.enabled }}
{{- $fullName := include "webapp.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    - http
  routes:
    - match: "Host(`{{ .Values.ingress.host }}`)"
      kind: Rule
      services:
        - name: {{ $fullName }}
          port: {{ $svcPort }}
{{- if .Values.ingress.tlsEnabled }}
      middlewares:
        - name: {{ $fullName }}-tls
{{- end -}}
{{ end }}
